
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 12;
  public static final int DISTINTO = 23;
  public static final int PR_INT = 37;
  public static final int POR = 16;
  public static final int CHAR = 32;
  public static final int PR_FOR = 47;
  public static final int PR_TITULO = 56;
  public static final int PR_BREAK = 51;
  public static final int STR = 31;
  public static final int EQUALS = 20;
  public static final int ENTERO = 27;
  public static final int PR_VOID = 34;
  public static final int PR_IF = 45;
  public static final int PR_ELSE = 46;
  public static final int PR_TITULOY = 60;
  public static final int LLAVIZQ = 6;
  public static final int PR_TITULOX = 59;
  public static final int PR_WHILE = 52;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int PR_NEWVALOR = 44;
  public static final int MAYORQUE = 19;
  public static final int IGUAL = 9;
  public static final int CORDER = 7;
  public static final int DIVIDIDO = 17;
  public static final int OR = 25;
  public static final int PR_SWITCH = 48;
  public static final int UMENOS = 33;
  public static final int ID = 30;
  public static final int PR_VALORES = 58;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int DECIMAL = 28;
  public static final int MAYOROIGUAL = 21;
  public static final int PR_GBARRAS = 54;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int PR_DGLOBALES = 36;
  public static final int MENOS = 15;
  public static final int PR_STRING = 38;
  public static final int PR_CHAR = 39;
  public static final int vacio = 61;
  public static final int MENOROIGUAL = 22;
  public static final int MENORQUE = 18;
  public static final int LLAVDER = 5;
  public static final int PR_CASE = 49;
  public static final int PUNTO = 10;
  public static final int PR_DO = 53;
  public static final int PR_DEFAULT = 50;
  public static final int PR_WRITE = 43;
  public static final int DOLLAR = 13;
  public static final int PR_EJEX = 57;
  public static final int PTCOMA = 2;
  public static final int BOOLEANO = 29;
  public static final int PR_GPIE = 55;
  public static final int PR_BOOL = 41;
  public static final int PARDER = 4;
  public static final int CORIZQ = 8;
  public static final int PR_DOUBLE = 40;
  public static final int PR_CONSOLE = 42;
  public static final int PR_MAIN = 35;
  public static final int MAS = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "LLAVDER",
  "LLAVIZQ",
  "CORDER",
  "CORIZQ",
  "IGUAL",
  "PUNTO",
  "COMA",
  "DOSPUNTOS",
  "DOLLAR",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "MENORQUE",
  "MAYORQUE",
  "EQUALS",
  "MAYOROIGUAL",
  "MENOROIGUAL",
  "DISTINTO",
  "AND",
  "OR",
  "NOT",
  "ENTERO",
  "DECIMAL",
  "BOOLEANO",
  "ID",
  "STR",
  "CHAR",
  "UMENOS",
  "PR_VOID",
  "PR_MAIN",
  "PR_DGLOBALES",
  "PR_INT",
  "PR_STRING",
  "PR_CHAR",
  "PR_DOUBLE",
  "PR_BOOL",
  "PR_CONSOLE",
  "PR_WRITE",
  "PR_NEWVALOR",
  "PR_IF",
  "PR_ELSE",
  "PR_FOR",
  "PR_SWITCH",
  "PR_CASE",
  "PR_DEFAULT",
  "PR_BREAK",
  "PR_WHILE",
  "PR_DO",
  "PR_GBARRAS",
  "PR_GPIE",
  "PR_TITULO",
  "PR_EJEX",
  "PR_VALORES",
  "PR_TITULOX",
  "PR_TITULOY",
  "vacio"
  };
}

